INSERT INTO PERFILUSUARIO (ID_PERFIL_USUARIO, PERFIL) VALUES (1, 'ADMINISTRADOR');
INSERT INTO PERFILUSUARIO (ID_PERFIL_USUARIO, PERFIL) VALUES (2, 'FUNCIONARIO');

INSERT INTO USUARIO (IDUSUARIO, LOGIN, SENHA) VALUES (1, 'Usuario admin', '$2a$10$zDOin6qKMSsrHhTLCn1Rxe/CZBZ8XpUjGgIx/c.ijSSuE4YAZVqWK');
INSERT INTO USUARIO (IDUSUARIO, LOGIN, SENHA) VALUES (2, 'Usuario comum', '$2a$10$FRiFLnVoAxbkifLithaEZ.PgKyr3acjtBlajaE6nCI5uK8TQjKkyW');

INSERT INTO USUARIO_PERFIL (USUARIO_ID, PERFIL_ID) VALUES (1,1);
INSERT INTO USUARIO_PERFIL (USUARIO_ID, PERFIL_ID) VALUES (2,2);
